[tox]
# Define a versão do Python que você está usando
envlist = py313
skipsdist = True

[testenv]
# Passo 1: Instala as dependências do seu requirements.txt
deps = -rrequirements.txt

# Passo 2: Comandos que o Tox vai executar em ordem
commands =
    # Testa se o arquivo de configuração e o Pydantic estão ok
    python src/core.py
    
    # Testa se o pipeline de dados (Ingestão e Preparação) roda sem erros
    python src/app.py